"""empty message

Revision ID: 61c4914c0a3d
Revises: 201ff05d0ed6
Create Date: 2021-03-02 00:09:25.489179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c4914c0a3d'
down_revision = '201ff05d0ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user', table_name='tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user', 'tasks', ['user'], unique=True)
    # ### end Alembic commands ###
